Apply linting/formatting

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -4,14 +4,14 @@
 git stash -k -u -q
 
 # Run the resume generator script
-python3 "$(git rev-parse --show-toplevel)/generator.py"
+python3 "$(git rev-parse --show-toplevel || true)/generator.py"
 
 # Check the exit status of the script
 if [ $? -ne 0 ]; then
-    echo "Pre-commit hook failed. Please fix the issues before committing."
-    # Restore the stashed changes
-    git stash pop -q
-    exit 1
+	echo "Pre-commit hook failed. Please fix the issues before committing."
+	# Restore the stashed changes
+	git stash pop -q
+	exit 1
 fi
 
 # Add the resultant files
